apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: ap-southeast-1
  version: "1.31"

vpc:
  id: vpc-xxxxx
  subnets:
    public:
      ap-southeast-1a:
        id: subnet-yyyyy1
      ap-southeast-1b:
        id: subnet-yyyyy2
    private:
      ap-southeast-1a:
        id: subnet-zzzzz1
      ap-southeast-1b:
        id: subnet-zzzzz2
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

fargateProfiles:
  - name: fargate-default
    selectors:
      - namespace: default
      - namespace: kube-system

iam:
  withOIDC: true
