apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: ap-southeast-1
  version: "1.31"

vpc:
  id: vpc-1111111111111
  subnets:
    public:
      ap-southeast-1a:
        id: subnet-111111111
      ap-southeast-1b:
        id: subnet-222222222
    private:
      ap-southeast-1a:
        id: subnet-3333333
      ap-southeast-1b:
        id: subnet-4444444
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

fargateProfiles:
  - name: fargate-default
    selectors:
      - namespace: default
      - namespace: kube-system

iam:
  withOIDC: true
